version: '3'
services:
  web:
    build: .
    command: npm run start
    container_name: 'amd-hunt-web'
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
